/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlogDetail: typeof import('./components/BlogDetail.vue')['default']
    Bloggird: typeof import('./components/Bloggird.vue')['default']
    BlogGrid: typeof import('./components/BlogGrid.vue')['default']
    BlogGrird: typeof import('./components/BlogGrird.vue')['default']
    ClassesHome: typeof import('./components/ClassesHome.vue')['default']
    ClassesMain: typeof import('./components/ClassesMain.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FooterAdmin: typeof import('./components/admin/FooterAdmin.vue')['default']
    GalleryHome: typeof import('./components/GalleryHome.vue')['default']
    Login: typeof import('./components/admin/Login.vue')['default']
    Modal: typeof import('./components/admin/Modal.vue')['default']
    NavbarAdmin: typeof import('./components/admin/NavbarAdmin.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./components/admin/StatCard.vue')['default']
    TeachersFooter: typeof import('./components/admin/teachers/TeachersFooter.vue')['default']
    TeachersHome: typeof import('./components/TeachersHome.vue')['default']
    TeachersMain: typeof import('./components/TeachersMain.vue')['default']
    TheAbout: typeof import('./components/TheAbout.vue')['default']
    TheClasses: typeof import('./components/TheClasses.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheGallery: typeof import('./components/TheGallery.vue')['default']
    TheHome: typeof import('./components/TheHome.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheTeachers: typeof import('./components/TheTeachers.vue')['default']
    YjeGallery: typeof import('./components/YjeGallery.vue')['default']
  }
}
