/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/admin/blogdetail': RouteRecordInfo<'/admin/blogdetail', '/admin/blogdetail', Record<never, never>, Record<never, never>>,
    '/admin/bloggrid': RouteRecordInfo<'/admin/bloggrid', '/admin/bloggrid', Record<never, never>, Record<never, never>>,
    '/admin/contact': RouteRecordInfo<'/admin/contact', '/admin/contact', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/gallery': RouteRecordInfo<'/admin/gallery', '/admin/gallery', Record<never, never>, Record<never, never>>,
    '/admin/information': RouteRecordInfo<'/admin/information', '/admin/information', Record<never, never>, Record<never, never>>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/orders': RouteRecordInfo<'/admin/orders', '/admin/orders', Record<never, never>, Record<never, never>>,
    '/admin/products': RouteRecordInfo<'/admin/products', '/admin/products', Record<never, never>, Record<never, never>>,
    '/blogdetail': RouteRecordInfo<'/blogdetail', '/blogdetail', Record<never, never>, Record<never, never>>,
    '/bloggrid': RouteRecordInfo<'/bloggrid', '/bloggrid', Record<never, never>, Record<never, never>>,
    '/classes': RouteRecordInfo<'/classes', '/classes', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/gallery': RouteRecordInfo<'/gallery', '/gallery', Record<never, never>, Record<never, never>>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/teachers': RouteRecordInfo<'/teachers', '/teachers', Record<never, never>, Record<never, never>>,
  }
}
